# Librerias

Las **librerias** o **bibliotecas** de Python son colecciones de módulos y funciones predefinidas que permiten a los usuarios ahorrar tiempo y esfuerzo al utilizar código ya creado y probado para realizar tareas específicas.

## Numpy

In [1]:
import numpy as np

### Vectores

Es un arreglo unimensional. Es una matriz de una sola columna.

In [2]:
vector = np.array ([1, 2, 3, 4, 5])

In [4]:
print(vector)

[1 2 3 4 5]


In [5]:
type (vector)

numpy.ndarray

In [8]:
# Nos muestra el tipo de informacion de cada valor, son valores enteros en 32 bits

vector.dtype

dtype('int32')

In [9]:
# Podemos hacer como en el caso de listas

vector [::2]

array([1, 3, 5])

In [10]:
# Podemos convertir la información en numeros enteros a float para trabajar normal, pese a que nos siga saliendo dtype('int32') al usar esta conversion ya son datos de tipo float

vector.astype (float)

array([1., 2., 3., 4., 5.])

In [11]:
vector.dtype

dtype('int32')

In [15]:
# Extraer datos

vector [2:5]

array([3, 4, 5])

In [13]:
# Cambiar el valor de una posicion

vector [0] = 10
print (vector)

[10  2  3  4  5]


In [17]:
# Copiar un vector para mantener su formato original

copia_vector = vector.copy ()

In [18]:
copia_vector [2] = 5

In [19]:
print (copia_vector)
print (vector)

[10  2  5  4  5]
[10  2  3  4  5]


In [28]:
# Podemos ordenar vectores

vector_desordenado = np.array ([3, 1, 2, 5, 4, 8, 7, 10, 14, 12, 20])

In [29]:
np.sort (vector_desordenado)

array([ 1,  2,  3,  4,  5,  7,  8, 10, 12, 14, 20])

## Matrices

Vector: Es una lista de valores separados por coma.
Matrices: Es una lista conformada por una lista con valores.

In [34]:
matriz = np.array ([[1, 2, 3, 4], [4, 5, 6, 4], [7, 8, 9, 4]])
print (matriz)

[[1 2 3 4]
 [4 5 6 4]
 [7 8 9 4]]


In [35]:
# Para saber el tamaño de una matriz (dimensiones)

matriz.shape 

(3, 4)

In [36]:
# Para saber el numero de elementos de una matriz

matriz.size

12

In [37]:
# Mostrar la primera fila de todas las columnas

matriz [0, :]

array([1, 2, 3, 4])

In [38]:
# Mostrar todas las filas y todas las columnas

matriz [:,:]

array([[1, 2, 3, 4],
       [4, 5, 6, 4],
       [7, 8, 9, 4]])

In [39]:
# Mostrar la primera columna de la fila 1

matriz [:,1]

array([2, 5, 8])

In [44]:
# Mostrar todas las filas menos la 1

matriz [1:, :]

array([[4, 5, 6, 4],
       [7, 8, 9, 4]])

In [45]:
# Cambiar las dimensiones de una matriz: Pasar columnas a filas, etc. Debemos convertir a una matriz que cuadre con el numero de elementos, sino saldra error

matriz.size

12

In [46]:
matriz.reshape ((4, 3))

array([[1, 2, 3],
       [4, 4, 5],
       [6, 4, 7],
       [8, 9, 4]])

In [48]:
# Convertir la matriz a un vector

matriz.reshape ((1, 12))

array([[1, 2, 3, 4, 4, 5, 6, 4, 7, 8, 9, 4]])

In [49]:
# Calcular la traspuesta

matriz

array([[1, 2, 3, 4],
       [4, 5, 6, 4],
       [7, 8, 9, 4]])

In [50]:
matriz.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9],
       [4, 4, 4]])

In [51]:
# Aplanar la matriz

matriz.flatten ()

array([1, 2, 3, 4, 4, 5, 6, 4, 7, 8, 9, 4])

**Operar entre matrices:**

In [52]:
A = np.array ([[1, 2], [3, 4]])
B = np.array ([[-1, 0], [0, -1]])

In [53]:
print (A)
print (B)

[[1 2]
 [3 4]]
[[-1  0]
 [ 0 -1]]


In [54]:
# Une una matriz al lado de la otra (de forma horizontal)

np.hstack ([A, B])

array([[ 1,  2, -1,  0],
       [ 3,  4,  0, -1]])

In [55]:
# Une una matriz al lado de la otra (de forma vertical)

np.vstack ([A, B])

array([[ 1,  2],
       [ 3,  4],
       [-1,  0],
       [ 0, -1]])

In [56]:
# Otras formas de hacer lo mismo es mediante concatenacion

# En el eje vertical

np.concatenate ([A, B], axis = 0)

array([[ 1,  2],
       [ 3,  4],
       [-1,  0],
       [ 0, -1]])

In [57]:
np.concatenate ([A, B], axis = 1)

array([[ 1,  2, -1,  0],
       [ 3,  4,  0, -1]])

In [59]:
# Crear una matriz de ceros o unos

np.zeros (shape = (3,3))



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.ones (shape = (3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Algebra lineal

Para poder operar con vectores y matrices

In [61]:
v1 = np.array ([1, 2, 3])
v2 = np.array ([4, 5, 6])

In [62]:
print (v1 + v2)

[5 7 9]


In [63]:
print (v1 - v2)

[-3 -3 -3]


In [64]:
print (v1 * v2)

[ 4 10 18]


In [65]:
print (v1 / v2)

[0.25 0.4  0.5 ]


In [66]:
# Calcular el productor punto, multiplica y suma

np.dot (v1, v2)

32

## Arreglo de booleanos

In [67]:
x = np.array ([1, 2, 3, 4, 5])
print (x)

[1 2 3 4 5]


In [68]:
# Decir con una condicion que me diga que vales son verdaderos o falsos

mask = x > 2
print (mask)


[False False  True  True  True]


In [69]:
# Usando where otra forma de filtrar la data

np.where (x > 2)

(array([2, 3, 4], dtype=int64),)

In [70]:
# Reemplazar los valores mayores que 2 con 0 y los que sean menores o iguales a 2 con 1

np.where (x > 2, 0, 1)

array([1, 1, 0, 0, 0])

### Medidas estadisticas

In [75]:
print (x)

[1 2 3 4 5]


In [71]:
x.sum()

15

In [72]:
x. max()

5

In [73]:
x.min()

1

In [74]:
x.mean()

3.0

In [76]:
# Varianza

x.var()

2.0

In [77]:
# Desviacion estandar

x.std()

1.4142135623730951

## Constantes de numpy

In [79]:
# Infinito

np.inf

inf

In [80]:
# Valor nulo

np.nan

nan

In [81]:
# e ...euler number?

np.e



2.718281828459045

In [82]:
# pi

np.pi

3.141592653589793

## Espacios lineales

Lo mas importante del curso

In [85]:
# Hace un arreglo entre valores de 1 a 9

np.arange (1, 10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
# Una manera mas usada. Se usa para los arreglos los espacios lineales entre tendidos de arreglo de electrodos

np.linspace (1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [88]:
# Para arreglos en ensayos geofisicos:

# 64 electrodos en un tendido de 200 m

np.linspace (1, 200, 64)

array([  1.        ,   4.15873016,   7.31746032,  10.47619048,
        13.63492063,  16.79365079,  19.95238095,  23.11111111,
        26.26984127,  29.42857143,  32.58730159,  35.74603175,
        38.9047619 ,  42.06349206,  45.22222222,  48.38095238,
        51.53968254,  54.6984127 ,  57.85714286,  61.01587302,
        64.17460317,  67.33333333,  70.49206349,  73.65079365,
        76.80952381,  79.96825397,  83.12698413,  86.28571429,
        89.44444444,  92.6031746 ,  95.76190476,  98.92063492,
       102.07936508, 105.23809524, 108.3968254 , 111.55555556,
       114.71428571, 117.87301587, 121.03174603, 124.19047619,
       127.34920635, 130.50793651, 133.66666667, 136.82539683,
       139.98412698, 143.14285714, 146.3015873 , 149.46031746,
       152.61904762, 155.77777778, 158.93650794, 162.0952381 ,
       165.25396825, 168.41269841, 171.57142857, 174.73015873,
       177.88888889, 181.04761905, 184.20634921, 187.36507937,
       190.52380952, 193.68253968, 196.84126984, 200.  

### Aleatorios

In [89]:
# Genera valores aleatorios

np.random.random (10)

array([0.01387556, 0.05046549, 0.91021121, 0.85239522, 0.76899103,
       0.11258976, 0.55783931, 0.47636522, 0.33038303, 0.87472753])

In [3]:
# Generar valores aleatorios entre 0 y 1

rng = np.random.default_rng()

In [91]:
rng.random ()

0.4272762538236261

In [92]:
rng.uniform (0,5)

2.3615822236005513

In [93]:
rng.integers (0,5)

3

In [94]:
# Una matriz con valores aleatorios

rng.normal (size=(2,2))

array([[ 1.38571076, -0.17188262],
       [-1.32768529, -0.15726715]])

In [4]:
rng.uniform (0,5)


4.959416777027145